name: Reusable Windows MSI

on:
  workflow_call:
    inputs:
      os:
        description: OS to run on
        required: true
        type: string
      arch:
        description: CPU architecture
        required: true
        type: string

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: installer for ${{ inputs.arch }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    env:
      ARCH: ${{ inputs.arch }}
      IncludeFreethreaded: true
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Build CPython installer
      # Forks don't have access to Windows on Arm runners. Skip those:
      if: inputs.arch != 'arm64' || github.repository_owner == 'python'
      run: ./Tools/msi/build.bat --doc -"${ARCH}"
      shell: bash
